name: Deploy Dev2 VPS (Self-hosted)

on:
  push:
    branches: [ dev ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull and migrate
        env:
          SUPABASE_DB_URL_DEV2: ${{ secrets.SUPABASE_DB_URL_DEV2 }}
        run: |
          set -e
          echo "pwd: $(pwd)"
          cd /home/joaohenrique/workspaces/projects/tricket
          echo "Repo remote URLs:"
          git remote -v || true
          git fetch --all --prune
          git checkout dev
          git pull --ff-only

          echo "Checking Supabase CLI..."
          if ! command -v supabase >/dev/null 2>&1; then
            echo "ERRO: Supabase CLI não encontrado no PATH do runner" >&2
            exit 1
          fi
          supabase --version

          if [ -z "${SUPABASE_DB_URL_DEV2}" ]; then
            echo "ERRO: Secret SUPABASE_DB_URL_DEV2 não definido" >&2
            exit 1
          fi

          cd tricket-backend
          echo "Executando supabase db push..."
          supabase db push --yes --db-url "${SUPABASE_DB_URL_DEV2}"
