/**********************************************************************************************************************
*   AUTO-GENERATED IMPORT: Import marketplace_gpc_to_tricket_category_mapping from CSV with upsert
*   This file was generated by storage-migration/generate_csv_inserts.py
*   It inserts/updates records based on CSV content.
*   Idempotent via ON CONFLICT.
**********************************************************************************************************************/

BEGIN;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000005', 'Legumes | Não preparados | Não processados Congelados', NULL, 'PENDENT', '2025-08-05 09:18:07.753705+00'::timestamptz, '2025-08-05 09:18:07.753705+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000016', 'Peixe | Preparado | Processado Perecível', NULL, 'PENDENT', '2025-08-05 09:03:14.19646+00'::timestamptz, '2025-08-05 09:03:14.19646+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000026', 'Leite / Substitutos do leite (Não perecível)', NULL, 'PENDENT', '2025-08-05 09:05:32.953936+00'::timestamptz, '2025-08-05 09:05:32.953936+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000043', 'Açúcar / Substitutos do Açúcar (Não perecível)', NULL, 'PENDENT', '2025-08-04 18:04:35.739354+00'::timestamptz, '2025-08-04 18:04:35.739354+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000045', 'Chocolate / Substitutos do Chocolate para doces', NULL, 'PENDENT', '2025-08-08 12:24:21.655983+00'::timestamptz, '2025-08-08 12:24:21.655983+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000047', 'Doces de Confeitaria Substitutos/Doces', NULL, 'PENDENT', '2025-08-05 09:14:11.656524+00'::timestamptz, '2025-08-05 09:14:11.656524+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000049', 'Ervas / Temperos (Não perecíveis)', NULL, 'PENDENT', '2025-08-05 09:28:18.223938+00'::timestamptz, '2025-08-05 09:28:18.223938+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000054', 'Molhos / Condimentos / Coberturas/Patês/Marinadas (perecíveis)', NULL, 'PENDENT', '2025-08-06 12:48:09.480568+00'::timestamptz, '2025-08-06 12:48:09.480568+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000055', 'Molhos - Culinários (Perecíveis)', NULL, 'PENDENT', '2025-08-04 18:06:42.201527+00'::timestamptz, '2025-08-04 18:06:42.201527+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000057', 'Molhos - Culinários (Não perecíveis)', NULL, 'PENDENT', '2025-08-04 18:06:18.195604+00'::timestamptz, '2025-08-04 18:06:18.195604+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000111', 'Café / Substitutos do café - Grãos / Moído', NULL, 'PENDENT', '2025-08-06 12:42:29.493799+00'::timestamptz, '2025-08-06 12:42:29.493799+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000114', 'Café - Líquido/Prontos para Beber', NULL, 'PENDENT', '2025-08-06 12:52:48.807566+00'::timestamptz, '2025-08-06 12:52:48.807566+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000115', 'Café - Instantâneo Solúvel', NULL, 'PENDENT', '2025-08-06 12:36:46.81756+00'::timestamptz, '2025-08-06 12:36:46.81756+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000116', 'Chá - Saquinhos / A granel', NULL, 'PENDENT', '2025-08-08 12:20:14.181935+00'::timestamptz, '2025-08-08 12:20:14.181935+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000117', 'Chá | Instantâneo', NULL, 'PENDENT', '2025-08-08 12:08:26.172032+00'::timestamptz, '2025-08-08 12:08:26.172032+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000118', 'Chá - Líquido/Pronto para beber', NULL, 'PENDENT', '2025-08-08 12:21:48.679224+00'::timestamptz, '2025-08-08 12:21:48.679224+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000158', 'Insumos para Assar/Cozinhar (Não Perecível)', NULL, 'PENDENT', '2025-08-04 20:05:09.301269+00'::timestamptz, '2025-08-04 20:05:09.301269+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000159', 'Cerveja', NULL, 'PENDENT', '2025-08-08 12:12:40.592437+00'::timestamptz, '2025-08-08 12:12:40.592437+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000160', 'Bolachas/ Biscoitos (Perecíveis)', NULL, 'PENDENT', '2025-08-05 09:30:15.218664+00'::timestamptz, '2025-08-05 09:30:15.218664+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000161', 'Biscoitos / Bolachas (Não perecíveis)', NULL, 'PENDENT', '2025-08-05 09:28:25.368201+00'::timestamptz, '2025-08-05 09:28:25.368201+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000172', 'Bolos - Doces - (Não perecíveis)', NULL, 'PENDENT', '2025-08-05 09:39:47.352671+00'::timestamptz, '2025-08-05 09:39:47.352671+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000177', 'Batatinhas/Salgadinhos/Combinação de lanches - Natural / Extrudido', NULL, 'PENDENT', '2025-08-04 20:03:19.946946+00'::timestamptz, '2025-08-04 20:03:19.946946+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000178', 'Chocolate / Cacau / Malte - Não pronto para beber', NULL, 'PENDENT', '2025-08-04 18:02:24.716794+00'::timestamptz, '2025-08-04 18:02:24.716794+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000191', 'Bebidas lácteas - Prontas para consumo (perecível)', NULL, 'PENDENT', '2025-08-05 09:22:16.16053+00'::timestamptz, '2025-08-05 09:22:16.16053+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000192', 'Bebidas lácteas - Prontas para consumo (sem refrigeração)', NULL, 'PENDENT', '2025-08-04 18:03:52.207986+00'::timestamptz, '2025-08-04 18:03:52.207986+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000201', 'Bebidas aromatizadas - Prontas para beber', NULL, 'PENDENT', '2025-08-04 14:12:20.305559+00'::timestamptz, '2025-08-04 14:12:20.305559+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000203', 'Farinha | Cereal | Leguminosas Não perecível', NULL, 'PENDENT', '2025-08-04 20:04:29.767521+00'::timestamptz, '2025-08-04 20:04:29.767521+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000206', 'Frutas - Preparadas/Processadas (Não perecíveis)', NULL, 'PENDENT', '2025-08-05 09:17:03.426326+00'::timestamptz, '2025-08-05 09:17:03.426326+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000207', 'Misturas de Frutas/Nozes/Sementes - Preparadas/Processadas (Não perecíveis)', NULL, 'PENDENT', '2025-08-05 09:27:21.131+00'::timestamptz, '2025-08-05 09:27:21.131+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000223', 'Bebidas à base de suco - Prontas para beber (Não perecíveis)', NULL, 'PENDENT', '2025-08-05 09:26:49.132412+00'::timestamptz, '2025-08-05 09:26:49.132412+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000232', 'Água engarrafada', NULL, 'PENDENT', '2025-08-04 18:07:05.777042+00'::timestamptz, '2025-08-04 18:07:05.777042+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000235', 'Nozes/Sementes - Preparados/Processados (Perecíveis)', NULL, 'PENDENT', '2025-08-05 09:23:21.101365+00'::timestamptz, '2025-08-05 09:23:21.101365+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000236', 'Nozes/Sementes - Preparados/Processados (descascados)', NULL, 'PENDENT', '2025-08-05 09:23:11.670616+00'::timestamptz, '2025-08-05 09:23:11.670616+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000239', 'Azeitonas (Não perecíveis)', NULL, 'PENDENT', '2025-08-05 09:08:54.276296+00'::timestamptz, '2025-08-05 09:08:54.276296+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000256', 'Marisco Preparado / Processado (Congelado)', NULL, 'PENDENT', '2025-08-06 12:49:01.380528+00'::timestamptz, '2025-08-06 12:49:01.380528+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000263', 'Bebidas alcoólicas', NULL, 'PENDENT', '2025-08-04 18:10:06.440414+00'::timestamptz, '2025-08-04 18:10:06.440414+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000272', 'Legumes | Preparados | Processados Não perecíveis', NULL, 'PENDENT', '2025-08-05 09:20:34.145273+00'::timestamptz, '2025-08-05 09:20:34.145273+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000280', 'Molhos/Condimentos/Coberturas/Patês Salgados/Marinadas (Não perecíveis)', NULL, 'PENDENT', '2025-08-04 20:05:42.368767+00'::timestamptz, '2025-08-04 20:05:42.368767+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000284', 'Produtos à Base de Cereal - Prontos para Consumo (Não perecíveis)', NULL, 'PENDENT', '2025-08-08 12:11:01.411954+00'::timestamptz, '2025-08-08 12:11:01.411954+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000287', 'Barras de Cereais/Granola', NULL, 'PENDENT', '2025-08-05 09:16:38.455709+00'::timestamptz, '2025-08-05 09:16:38.455709+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000289', 'Produtos Hortícolas - Prontos para Consumo (Perecíveis)', NULL, 'PENDENT', '2025-08-05 09:08:22.163104+00'::timestamptz, '2025-08-05 09:08:22.163104+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000297', 'Produtos à base de Grãos - Não prontos para Consumo - Salgados (Não perecíveis)', NULL, 'PENDENT', '2025-08-06 12:50:28.283387+00'::timestamptz, '2025-08-06 12:50:28.283387+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000310', 'Bebidas lácteas - Não prontas para consumo (sem refrigeração)', NULL, 'PENDENT', '2025-08-05 09:27:37.233967+00'::timestamptz, '2025-08-05 09:27:37.233967+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000319', 'Grãos/Cereais - Prontos para o Consumo (Não Perecíveis)', NULL, 'PENDENT', '2025-08-04 20:09:29.858767+00'::timestamptz, '2025-08-04 20:09:29.858767+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000335', 'Produtos de algodão', NULL, 'PENDENT', '2025-08-04 19:35:12.621372+00'::timestamptz, '2025-08-04 19:35:12.621372+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000338', 'Antitranspirantes / Desodorantes', NULL, 'PENDENT', '2025-08-04 20:06:05.482478+00'::timestamptz, '2025-08-04 20:06:05.482478+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000397', 'Recursos para Limpeza', NULL, 'PENDENT', '2025-08-04 18:09:05.658723+00'::timestamptz, '2025-08-04 18:09:05.658723+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000405', 'Produtos para limpeza de superfície', NULL, 'PENDENT', '2025-08-04 19:34:44.677377+00'::timestamptz, '2025-08-04 19:34:44.677377+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000426', 'Produtos de Limpeza Sanitária', NULL, 'PENDENT', '2025-08-04 18:08:47.901527+00'::timestamptz, '2025-08-04 18:08:47.901527+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000468', 'Suplementos Nutricionais', NULL, 'PENDENT', '2025-08-05 09:15:34.630149+00'::timestamptz, '2025-08-05 09:15:34.630149+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000531', 'Alvejante', NULL, 'PENDENT', '2025-08-04 19:37:14.170077+00'::timestamptz, '2025-08-04 19:37:14.170077+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000590', 'Pacotes de Variedades para Alimentos|Bebidas|Tabaco', NULL, 'PENDENT', '2025-08-04 18:03:10.019116+00'::timestamptz, '2025-08-04 18:03:10.019116+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000592', 'Pacotes de Variedades para Café / Chá / Substitutos', NULL, 'PENDENT', '2025-08-04 18:04:02.887765+00'::timestamptz, '2025-08-04 18:04:02.887765+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000599', 'Pacotes de Variedade para Grãos/Farinha de trigo', NULL, 'PENDENT', '2025-08-04 20:08:19.251179+00'::timestamptz, '2025-08-04 20:08:19.251179+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000601', 'Pacotes de Variedade de Produtos para Cereais/Grãos', NULL, 'PENDENT', '2025-08-04 20:08:34.160288+00'::timestamptz, '2025-08-04 20:08:34.160288+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000613', 'Pacotes de Variedades para Alimentos Preparados |Conservados', NULL, 'PENDENT', '2025-08-04 18:03:26.889212+00'::timestamptz, '2025-08-04 18:03:26.889212+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000614', 'Pacotes de Variedades para Frutos do Mar', NULL, 'PENDENT', '2025-08-05 09:04:25.084843+00'::timestamptz, '2025-08-05 09:04:25.084843+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000615', 'Pacotes de Variedades para Ervas/Temperos/Extratos', NULL, 'PENDENT', '2025-08-06 12:46:51.952046+00'::timestamptz, '2025-08-06 12:46:51.952046+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000617', 'Pacotes de Variedades para Molhos/Patês/Caldos/Condimentos', NULL, 'PENDENT', '2025-08-08 12:09:33.058725+00'::timestamptz, '2025-08-08 12:09:33.058725+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000619', 'Pacotes de Variedades para Temperos/Conservantes/Extratos', NULL, 'PENDENT', '2025-08-06 12:47:05.977201+00'::timestamptz, '2025-08-06 12:47:05.977201+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000622', 'Pacotes de Variedades para Confeitos / Edulcorantes', NULL, 'PENDENT', '2025-08-08 12:25:53.581073+00'::timestamptz, '2025-08-08 12:25:53.581073+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000623', 'Pacotes de Variedades para Bebidas', NULL, 'PENDENT', '2025-08-04 18:07:14.896245+00'::timestamptz, '2025-08-04 18:07:14.896245+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000666', 'Pacotes de Variedades para Higiene/Cuidados Pessoais/Beleza', NULL, 'PENDENT', '2025-08-04 20:05:16.890562+00'::timestamptz, '2025-08-04 20:05:16.890562+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000693', 'Embalagem para Alimentos Descartável', NULL, 'PENDENT', '2025-08-05 09:15:19.290115+00'::timestamptz, '2025-08-05 09:15:19.290115+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000694', 'Pacotes de Variedade para Produtos de Limpeza/Higiene', NULL, 'PENDENT', '2025-08-04 19:37:22.056975+00'::timestamptz, '2025-08-04 19:37:22.056975+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000740', 'Amaciantes - Tecido', NULL, 'PENDENT', '2025-08-04 19:55:01.82708+00'::timestamptz, '2025-08-04 19:55:01.82708+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000744', 'Amaciantes de roupas', NULL, 'PENDENT', '2025-08-04 19:37:38.30727+00'::timestamptz, '2025-08-04 19:37:38.30727+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000746', 'Outros produtos de limpeza', NULL, 'PENDENT', '2025-08-08 12:29:15.774865+00'::timestamptz, '2025-08-08 12:29:15.774865+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000834', 'Outros Produtos de Cuidados com os Cabelos', NULL, 'PENDENT', '2025-08-04 20:10:17.279135+00'::timestamptz, '2025-08-04 20:10:17.279135+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000841', 'Outros Recursos para Dieta', NULL, 'PENDENT', '2025-08-04 18:06:49.974843+00'::timestamptz, '2025-08-04 18:06:49.974843+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10000908', 'Outros produtos para Primeiros Socorros', NULL, 'PENDENT', '2025-08-04 19:35:56.865456+00'::timestamptz, '2025-08-04 19:35:56.865456+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10005227', 'Produtos à base de Leite / Ovos - Prontos para consumo (Perecíveis)', NULL, 'PENDENT', '2025-08-05 09:21:50.002291+00'::timestamptz, '2025-08-05 09:21:50.002291+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10005767', 'Carne bovina - Preparada / Processada', NULL, 'PENDENT', '2025-08-04 19:36:22.653222+00'::timestamptz, '2025-08-04 19:36:22.653222+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10005769', 'Carne de frango - Preparada / Processada', NULL, 'PENDENT', '2025-08-05 09:05:14.504211+00'::timestamptz, '2025-08-05 09:05:14.504211+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10005781', 'Carne de porco - Preparada / Processada', NULL, 'PENDENT', '2025-08-05 09:11:35.309346+00'::timestamptz, '2025-08-05 09:11:35.309346+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10005786', 'Carne bovina- Não preparada/não processada', NULL, 'PENDENT', '2025-08-05 09:28:09.562769+00'::timestamptz, '2025-08-05 09:28:09.562769+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10005788', 'Frango- Não preparado / não processado', NULL, 'PENDENT', '2025-08-04 20:10:01.682213+00'::timestamptz, '2025-08-04 20:10:01.682213+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10005823', 'Substitutos da carne (congelada)', NULL, 'PENDENT', '2025-08-04 19:37:06.101925+00'::timestamptz, '2025-08-04 19:37:06.101925+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10005923', 'Amoras', NULL, 'PENDENT', '2025-08-04 20:05:25.721438+00'::timestamptz, '2025-08-04 20:05:25.721438+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10006006', 'Cebolas', NULL, 'PENDENT', '2025-08-04 20:05:33.772431+00'::timestamptz, '2025-08-04 20:05:33.772431+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10006104', 'Batatas', NULL, 'PENDENT', '2025-08-05 09:18:32.257527+00'::timestamptz, '2025-08-05 09:18:32.257527+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10006311', 'Substitutos de Café - Instantâneo Solúvel', NULL, 'PENDENT', '2025-08-06 12:51:50.529743+00'::timestamptz, '2025-08-06 12:51:50.529743+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10006324', 'Ketchup de Tomate/Substitutos de Ketchup (Perecíveis)', NULL, 'PENDENT', '2025-08-08 12:09:41.326666+00'::timestamptz, '2025-08-08 12:09:41.326666+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10006325', 'Ketchup de Tomate/Substitutos de Ketchup (Não refrigerados)', NULL, 'PENDENT', '2025-08-08 12:10:06.849072+00'::timestamptz, '2025-08-08 12:10:06.849072+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10006345', 'Kumquat', NULL, 'PENDENT', '2025-08-05 09:41:38.534122+00'::timestamptz, '2025-08-05 09:41:38.534122+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10006752', 'Refeições Combinadas Prontas - Pronto para Comer (Prateleira Estável)', NULL, 'PENDENT', '2025-08-05 09:02:56.048631+00'::timestamptz, '2025-08-05 09:02:56.048631+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10006973', 'Bebidas à base de substitutos de laticínios - Prontas para consumo (sem refrigeração)', NULL, 'PENDENT', '2025-08-05 09:23:28.990052+00'::timestamptz, '2025-08-05 09:23:28.990052+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10007880', 'Canela (Cinnamomum Verum)', NULL, 'PENDENT', '2025-08-06 12:49:46.835205+00'::timestamptz, '2025-08-06 12:49:46.835205+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10008029', 'Cerveja (sem álcool)', NULL, 'PENDENT', '2025-08-08 12:16:55.401938+00'::timestamptz, '2025-08-08 12:16:55.401938+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10008178', 'Café - Grão', NULL, 'PENDENT', '2025-08-06 12:36:37.745613+00'::timestamptz, '2025-08-06 12:36:37.745613+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10008179', 'Café - Moído', NULL, 'PENDENT', '2025-08-06 12:36:03.833947+00'::timestamptz, '2025-08-06 12:36:03.833947+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '10008180', 'Café - Cápsulas', NULL, 'PENDENT', '2025-08-06 12:36:28.331651+00'::timestamptz, '2025-08-06 12:36:28.331651+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '47000000', 'Produtos de Limpeza / Higiene', NULL, 'PENDENT', '2025-08-04 19:40:08.267916+00'::timestamptz, '2025-08-04 19:40:08.267916+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '50000000', 'Alimentos/Bebidas/Tabaco', NULL, 'PENDENT', '2025-08-05 09:11:52.508811+00'::timestamptz, '2025-08-05 09:11:52.508811+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '50171800', 'Molhos/Entradas/Petiscos/Condimentos', NULL, 'PENDENT', '2025-08-05 09:15:00.717021+00'::timestamptz, '2025-08-05 09:15:00.717021+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '50172000', 'Pacotes de Variedades para Temperos/Conservantes/Extratos', NULL, 'PENDENT', '2025-08-04 20:05:00.897233+00'::timestamptz, '2025-08-04 20:05:00.897233+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '50182100', 'Biscoitos/Bolachas', NULL, 'PENDENT', '2025-08-05 09:32:20.772212+00'::timestamptz, '2025-08-05 09:32:20.772212+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '50190000', 'Alimentos Preparados / Conservados', NULL, 'PENDENT', '2025-08-04 19:34:19.52331+00'::timestamptz, '2025-08-04 19:34:19.52331+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '50192100', 'Aperitivos', NULL, 'PENDENT', '2025-08-05 09:31:30.083263+00'::timestamptz, '2025-08-05 09:31:30.083263+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '50193500', 'Laticínios /Produtos à base de Ovos', NULL, 'PENDENT', '2025-08-05 09:23:04.051743+00'::timestamptz, '2025-08-05 09:23:04.051743+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '50200000', 'Bebidas', NULL, 'PENDENT', '2025-08-04 18:07:22.238102+00'::timestamptz, '2025-08-04 18:07:22.238102+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '50240000', 'Carne / Aves', NULL, 'PENDENT', '2025-08-04 19:34:28.232462+00'::timestamptz, '2025-08-04 19:34:28.232462+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

INSERT INTO public.marketplace_gpc_to_tricket_category_mapping (
  gpc_category_code, gpc_category_name, tricket_sub_category_id, status, created_at, updated_at
) VALUES (
  '72000000', 'Eletrodomésticos', NULL, 'PENDENT', '2025-08-05 09:14:37.582694+00'::timestamptz, '2025-08-05 09:14:37.582694+00'::timestamptz
)
ON CONFLICT (gpc_category_code) DO UPDATE SET
  gpc_category_name = EXCLUDED.gpc_category_name,
  tricket_sub_category_id = EXCLUDED.tricket_sub_category_id,
  status = EXCLUDED.status,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;


COMMIT;
